name: Deploy Hatchify Grid-Demo

on:
  push:
    branches: [461-move-hatchify-grid-demo]

permissions:
  contents: read

jobs:
  Hatchify-Deploy-Postgres:
    # if the branch name of the PR does not contain 'skip-deploy'
    if: !contains(github.head_ref, 'skip-deploy')
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
      - id: deploy-postgres
        name: Deploy with postgres
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          # Provide a secret called `DOT_ENV` to append environment variables to the .env file
          # dot_env: ${{ secrets.DOT_ENV }}
          aws_r53_enable: true
          aws_r53_domain_name: bitovi-sandbox.com
          aws_elb_app_port: 3000,3001
          aws_elb_listen_port: 3000,3001
          aws_elb_healthcheck: "HTTP:3000/"

          aws_ec2_instance_root_vol_size: 20
          aws_ec2_instance_type: t3.large
          aws_ec2_create_keypair_sm: true

          docker_full_cleanup: true
          docker_repo_app_directory: ../example/hatchify-grid-demo/docker-compose.yaml
          docker_repo_app_directory_cleanup: true

          #tf_stack_destroy: true
          tf_state_bucket_destroy: true
